services:
  juneogo:
    build: .
    container_name: juneogo
    restart: unless-stopped
    ports:
      # - 9650:9650 # port for API calls - will enable remote RPC calls to your node (mandatory for Supernet/ Blockchain deployers)
      - 9651:9651 # 9651 for staking

    volumes:
      - ./juneogo:/root
      - /etc/letsencrypt:/etc/letsencrypt
      - /etc/localtime:/etc/localtime:ro
    networks:
      slg-network:
        ipv4_address: 192.168.10.2

    command: bash -c "./config.sh && ./juneogo --config-file='.juneogo/config.json'"
    # Max-size of 10m and max-file of 3 to avoid filling up the disk
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'

  caddy:
    image: caddy:latest
    container_name: caddy
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/caddy_data:/data
      - ./caddy/caddy_config:/config
      - ./juneogo/.juneogo:/etc/juneogo-ssl:ro
      - ./caddy/scripts:/scripts
    env_file:
      - .env
    networks:
      slg-network:
        ipv4_address: 192.168.10.200

networks:
  slg-network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.10.0/24
          gateway: 192.168.10.1
