version: '2'

services:
  
  juneogo:
    build: .
    container_name: juneogo
    restart: unless-stopped
    ports:
      - 80:80 # 80 for Certbot
      - 443:443 # 443 for Certbot
      - 9650:9650
    
    volumes:
      - ./juneogo:/root
      - /etc/letsencrypt:/etc/letsencrypt
    networks:
      slg-network:
        ipv4_address: 192.168.10.2
    
    command: bash -c "./config.sh && ./obtain-ssl-certificates.sh archive1.mcnpoc4.xyz corentda@hotmail.fr && ./juneogo --config-file='.juneogo/config.json'"
    # command : tail -f /dev/null
 
networks:

    slg-network:
      driver: bridge
      ipam:
        config:
          - subnet: 192.168.10.0/24
            gateway: 192.168.10.1
