version: '2'

services:
  juneogo:
    build: .
    container_name: juneogo
    restart: unless-stopped
    ports:
      - 80:80 # 80 for Certbot
      - 443:443 # 443 for Certbot
      - 9650:9650 # 9650 for api
      - 9651:9651 # 9651 for staking

    volumes:
      - ./juneogo:/root
      - /etc/letsencrypt:/etc/letsencrypt
      - /etc/localtime:/etc/localtime:ro
    networks:
      slg-network:
        ipv4_address: 192.168.10.2

    command: bash -c "./config.sh && ./obtain-ssl-certificates.sh domain.com email@mail.fr && ./juneogo --config-file='.juneogo/config.json'"
    # put a max-size of 10m and max-file of 3 to avoid filling up the disk
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'

networks:
  slg-network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.10.0/24
          gateway: 192.168.10.1
